El programa funcionara en los datos ingresados tales como:
Edad
Estado Civil
Hijos

Extras
Propiedades y valor de estas
Salario por asegurar.


--------------------------------------------------------------------

Considere que el cargo a asegurar será basado en la edad.
Los recargos serán basados en la edad del conyugue y la cantidad de hijos.

Extras
El seguro para propiedades será el 35% del valor de estas.
El seguro para el salario será el 5% del salario total. 

--------------------------------------------------------------------
Para mejorar se podría recopilar más información del asegurado:
* Profesion.
* Información medica del asegurado y conyuge
* Edad de los hijos.

